name: "CONFIG COLLECTOR"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: php bot.php
      
      - name: Keep only last 50 configs
        run: |
          for file in Config/*.txt; do
            if [ -f "$file" ]; then
              tail -n 50 "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            fi
          done
      
      - name: Push changes
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git add -A
          git commit -m "V0.2 🚀 - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_BOT }}
