name: "CONFIG COLLECTOR"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: php bot.php
      
      - name: Merge all configs into one file
        run: |
          > all_configs.txt
          
          for file in sub/*; do
            if [ -f "$file" ]; then
              echo "📄 Processing: $file"
              if [[ "$file" != *base64* ]]; then
                cat "$file" >> all_configs.txt
                echo "" >> all_configs.txt
              fi
            fi
          done
          
          echo "✅ Total lines: $(wc -l < all_configs.txt)"
          echo "📊 First 5 lines:"
          head -n 5 all_configs.txt
      
      - name: Push changes
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git add -A
          git commit -m "Update - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push https://${{ secrets.PUSH_BOT }}@github.com/MAM-07-98/V2ray-Collector_mam1.git HEAD:main
